<?php
/**
 * Template File
 * This file is the help message template for the Admin Help tab of the Content Templates listing page.
 *
 * @since 2.5.0
 */
?>

<p><?php echo __( 'Use <strong>Content Templates</strong> to design single pages in your site.', 'wpv-views'); ?></p>
<p><?php echo __( 'This page lists the <strong>Content Templates</strong> that you have created and allows you to create new ones.', 'wpv-views' ); ?></p>
<p><?php echo __( 'The tabs menu at the top of the page lets you list the <strong>Content Templates</strong> by their name or by how they are used in the site.', 'wpv-views'); ?></p>
<p><?php echo __( 'Click on the name of a Content Template to edit it or create new <strong>Content Templates</strong> using the ‘Add’ buttons.', 'wpv-views'); ?></p>
<p>
	<a href="https://toolset.com/documentation/user-guides/view-templates/?utm_source=viewsplugin&utm_campaign=views&utm_medium=view-content-template-header-help&utm_term=Content Templates online help" target="_blank"><?php echo __( 'Content Templates online help', 'wpv-views' ); ?></a>
</p>