<?php
/**
 * Template File
 * This file is the help message template for the Admin Help tab of the Content Templates edit page.
 *
 * @since 2.5.0
 */
?>

<p><?php echo __( '<strong>Content Templates</strong> can be used to design single pages in your site.', 'wpv-views' ); ?></p>
<p><?php echo __( 'To create a <strong>Content Template</strong>:', 'wpv-views' ); ?></p>
<ol>
	<li><?php echo __( 'Set the title', 'wpv-views' ); ?></li>
	<li><?php echo __( 'Design the output for the <strong>Content Template</strong> by adding fields to the template and styling with HTML.', 'wpv-views' ); ?></li>
	<li><?php echo __( 'Select the content types that will use the <strong>Content Template</strong> to display their content.', 'wpv-views' ); ?></li>
</ol>
<p><?php echo __( 'When you are done, your <strong>Content Templates</strong> is ready. No further actions needed for it to be applied to the selected content types.', 'wpv-views' ); ?></p>
<p>
	<a href="https://toolset.com/documentation/user-guides/view-templates/?utm_source=viewsplugin&utm_campaign=views&utm_medium=view-content-template-header-help&utm_term=Content Templates online help" target="_blank"><?php echo __( 'Content Templates online help', 'wpv-views' ); ?></a>
</p>